python main.py sconv=True deform=True retrain=True experiment_name='dcnv3 crt'
python main.py sconv=True deform=True retrain=False experiment_name='dcnv3'
python main.py sconv=False deform=True retrain=True experiment_name='dcnv2 crt'
python main.py sconv=False deform=True retrain=False experiment_name='dcnv2'
python main.py sconv=True deform=False retrain=True experiment_name='separable conv crt'
python main.py sconv=False deform=False retrain=True experiment_name='separable conv'
python main.py sconv=False deform=False retrain=True experiment_name='CNN crt'
python main.py sconv=False deform=False retrain=False experiment_name='CNN'
python main.py sconv=False deform=False retrain=False kernel_size='[(4,1),(16,1),(1,6),(1,16)]' pooling='[2,2,2,2]' experiment_name='OblongCNN'
python main.py sconv=False deform=True retrain=True kernel_size='[(4,1),(16,1),(1,6),(1,16)]' pooling='[2,2,2,2]' experiment_name='OblongDeformableCNN'